<?php

/**
 * @file
 * Module file for explore D7 Ajax.
 */

/**
 * Implements hook_menu().
 */
function d7_ajax_menu() {
  $items = array();
  $items['d7-ajax-add-remove'] = array(
    'title' => 'Ajax Add/Remove',
    'page callback' => '_d7_ajax_add_remove',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['d7-ajax-my_form'] = array(
    'title' => 'Ajax',
    'page callback' => '_d7_ajax_my_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _d7_ajax_add_remove() {
  $form = drupal_get_form('ajax_add_remove_form');
  return drupal_render($form);
}

/**
 * Form with ajax Add/Remove functionality.
 */
function ajax_add_remove_form($form, &$form_state) {
  // Array stores the index/delta.
  $form_state['storage']['index_array'] = isset($form_state['storage']['index_array']) ? $form_state['storage']['index_array'] : array(0);

  // If button is clicked.
  if (isset($form_state['triggering_element'])) {
    $action = $form_state['clicked_button']['#action_type'];
    switch ($action) {
      case 'add':
        $form_state['storage']['index_array'][] = max($form_state['storage']['index_array']) + 1;
        break;
      case 'remove':
        $index_position = $form_state['clicked_button']['#index_position'];
        unset($form_state['storage']['index_array'][array_search($index_position, $form_state['storage']['index_array'])]);
        break;
    }
  }
  $form['my-fieldset'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#title' => t('My Fieldset'),
    '#prefix' => '<div id="my-fieldset-wrapper">',
    '#suffix' => '</div>',
  );
  foreach ($form_state['storage']['index_array'] as $key => $val) {
    $form['my-fieldset'][$val]['text'] = array(
      '#type' => 'textfield',
      '#title' => t('My Name'),
    );
    if (count($form_state['storage']['index_array']) > 1) {
      $form['my-fieldset'][$val]['remove'] = array(
        '#type' => 'button',
        '#value' => t('Remove_@val', array('@val' => $val)),
        '#ajax' => array(
          'callback' => '_d7_ajax_ajax_add_remove_callback',
          'wrapper' => 'my-fieldset-wrapper',
        ),
        '#action_type' => 'remove',
        '#index_position' => $val,
      );
    }
  }
  $form['my-fieldset']['add'] = array(
    '#type' => 'button',
    '#value' => t('Add another'),
    '#ajax' => array(
      'callback' => '_d7_ajax_ajax_add_remove_callback',
      'wrapper' => 'my-fieldset-wrapper',
     ),
    '#action_type' => 'add',
  );

  $form['submit'] = array(
    '#value' => t('Save'),
    '#type' => 'submit',
  );

  return $form;
}

/**
 * Ajax callback wrapper for the for add/remove.
 */
function _d7_ajax_ajax_add_remove_callback($form, $form_state) {
  return $form['my-fieldset'];
}

/**
 * Submit handler for the ajax_add_remove_form.
 */
function ajax_add_remove_form_submit($form, &$form_state) {
  drupal_set_message(t('Saved. Thankyou!'));
}

/**
 * Hook Menu callback.
 */
function _d7_ajax_my_form() {
  $args = arg();
  if (!empty($args[1])) {
    ctools_include('ajax');
    ctools_include('modal');
    $form_state = array(
      'title' => t('Ajax'),
      'ajax' => TRUE,
    );
    $output = ctools_modal_form_wrapper('_d7_ajax_country_state_form', $form_state);
    print ajax_render($output);
    exit;
  }
  else {
    $form = drupal_get_form('_d7_ajax_country_state_form');
    return drupal_render($form);
  }
}

/**
 * Form to ajaxify state based on country.
 */
function _d7_ajax_country_state_form($form, &$form_state) {
  $country_state = _d7_get_state_country();
  $states = array();
  if (isset($form_state['values']['country'])) {
    $states = $country_state[$form_state['values']['country']];
  }
  $form['country'] = array(
    '#type' => 'select',
    '#title' => t('Country'),
    '#options' => drupal_map_assoc(array_keys($country_state)),
    '#ajax' => array(
      'callback' => '_d7_state_country_ajax_callback',
      'wrapper' => 'my-states',
    ),
  );
  $form['state'] = array(
    '#type' => 'select',
    '#title' => t('State'),
    '#options' => $states,
    '#prefix' => '<div id="my-states">',
    '#suffix' => '</div>',
  );

  ctools_include('modal');
  ctools_include('ajax');
  ctools_modal_add_js();
  $form['link'] = array(
    '#type' => 'markup',
    '#markup' => '<div>' . ctools_modal_text_button(t('Click Here'), 'd7-ajax-my_form/ctools', 'click') . '</div>',
  );
  return $form;
}

/**
 * Ajax wrapper for the country / state form.
 */
function _d7_state_country_ajax_callback($form, $form_state) {
  return $form['state'];
}

/**
 * Get List of countries and their states.
 * @return type array
 */
function _d7_get_state_country() {
  return array(
    '1' => array(
      'state-1' => 'State 1',
      'state-2' => 'State 2',
    ),
    '2' => array(
      'state-3' => 'State 3',
      'state-4' => 'State 4',
    ),
    '3' => array(
      'state-5' => 'State 5',
      'state-6' => 'State 6',
    ),
  );
}
