<?php

/**
 * @file
 * Module file contains hooks and other stuff.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 * for 'field_ui_field_edit_form' form.
 */
function body_absolute_urls_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  // Fields for which absolute url needs to be enabled.
  $types_check = array('text_textarea_with_summary', 'text_textarea');
  // Only for textareas.
  if (in_array($form['#instance']['widget']['type'], $types_check)) {
    $default_value = isset($form['#field']['absolute_url_check']) ? $form['#field']['absolute_url_check'] : 0;
    $form['field']['absolute_url_check'] = array(
      '#type' => 'checkbox',
      '#title' => t('Check for absolute urls'),
      '#default_value' => $default_value,
    );
  }
}

/**
 * Implements hook_node_validate().
 */
function body_absolute_urls_node_validate($node, $form, &$form_state) {
  // Get name of those fields whose marked for absolute url check.
  foreach ($form_state['field'] as $field_name => $val) {
    if (isset($val[LANGUAGE_NONE]['field']['absolute_url_check']) && $val[LANGUAGE_NONE]['field']['absolute_url_check'] == 1) {

      foreach ($form_state['values'][$field_name][LANGUAGE_NONE] as $key => $value) {
        if (is_numeric($key)) {
          $text = $value['value'];
          $ref_pattern = '/(?<=href=\").+(?=\")/';

          // Check for the anchor tag pattern in text.
          if (preg_match($ref_pattern, $text, $matches)) {
            // If there are some links in the text.
            foreach ($matches as $match) {

              // If absolute url contains the site's url.
              if (_body_abdolute_url_match_site_url($match)) {
                form_set_error($field_name, t('There is an absolute url present in the @field_name.', array('@field_name' => $field_name)));
                break;
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_links().
 */
function body_absolute_urls_preprocess_links(&$variables) {
  foreach ($variables['links'] as &$link) {
    //$link['attributes']['class'][] = 'ajax-link';
    //$link['attributes']['rel'] = '#content';
  }
}

/**
 * Method to check whether passed url contains the site url or not.
 * @param type $match
 * @return bool
 *  If matches return true, false otherwise.
 */
function _body_abdolute_url_match_site_url($match) {
  global $base_url;

  // Get the base url of site (removing https, other protocals).
  $url_components = parse_url($base_url);
  $site_url = $url_components['host'] . $url_components['path'];

  // Check if string contains the site url in it.
  if (strpos($match, $site_url) !== FALSE) {
    return TRUE;
  }
  return FALSE;
}
