<?php

/**
 * @file
 * Module file contains hooks and other stuff.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 * for 'field_ui_field_edit_form' form.
 */
function body_absolute_urls_form_field_ui_field_edit_form_alter(&$form, &$form_state) {

  // Only for textareas.
  if ($form['#instance']['widget']['type'] == 'text_textarea') {
    $default_value = isset($form['#field']['absolute_url_check']) ? $form['#field']['absolute_url_check'] : 0;
    $form['field']['absolute_url_check'] = array(
      '#type' => 'checkbox',
      '#title' => t('Check for absolute urls'),
      '#default_value' => $default_value,
    );
  }
}

/**
 * Implements hook_node_validate().
 */
function body_absolute_urls_node_validate($node, $form, &$form_state) {
  global $base_url;
  $url_components = parse_url($base_url);
  $site_url = $url_components['host'] . $url_components['path'];

  $absolute_url_present = FALSE;
  $text = $form_state['values']['body']['und'][0]['value'];
  $ref_pattern = '/(?<=href=\").+(?=\")/';
  //$ref_pattern = '/href=["\']?([^"\'>]+)["\']?/';

  // Check for the anchor tag pattern in text.
  if (preg_match($ref_pattern, $text, $matches)) {
    // If there are some links in the text.
    foreach ($matches as $match) {

      // If absolute url contains the site's url.
      if (strpos($match, $site_url) !== FALSE) {
        $absolute_url_present = TRUE;
        break;
      }
    }
  }

  // If absolute url is present in text.
  if ($absolute_url_present) {
    form_set_error('body', t('There is an absolute url present in the body.'));
  }
}

/**
 * Implements hook_preprocess_links().
 */
function body_absolute_urls_preprocess_links(&$variables) {
  foreach ($variables['links'] as &$link) {
    $link['attributes']['class'][] = 'ajax-link';
    $link['attributes']['rel'] = '#content';
  }
}
